require(RSQLite)
require(dplyr)
db <- src_sqlite('database.sqlite', create = F)
AdsInfo <- db %>% tbl('AdsInfo')
UserInfo <- db %>% tbl('UserInfo')
Category <- db %>% tbl('Category')
Location <- db %>% tbl('Location')
PhoneRequestsStream <- db %>% tbl('PhoneRequestsStream')
SearchInfo <- db %>% tbl('SearchInfo')
trainSearchStream <- db %>% tbl('trainSearchStream')

AdsInfo %>% glimpse()
UserInfo %>% glimpse()
Category %>% glimpse()
Location %>% glimpse()
PhoneRequestsStream %>% glimpse()
SearchInfo %>% glimpse()
trainSearchStream %>% glimpse()


library(dplyr)
db <- src_sqlite("database.sqlite")
src_tbls(db)
testSearchStream <- tbl(db,sql("select * from testSearchStream"))
AdsInfo <- tbl(db,sql("select * from AdsInfo"))
UserInfo <- tbl(db,sql("select * from UserInfo"))
Category <- tbl(db,sql("select * from Category"))
Location <- tbl(db,sql("select * from Location"))
PhoneRequestsStream <- tbl(db,sql("select * from PhoneRequestsStream"))
trainSearchStream <- tbl(db,sql("select * from trainSearchStream"))

write.csv(testSearchStream, "testSearchStream.csv")
write.csv(AdsInfo, "AdsInfo.csv")
write.csv(UserInfo, "UserInfo.csv")
write.csv(Category, "Category.csv")
write.csv(Location, "Location.csv")
write.csv(PhoneRequestsStream, "PhoneRequestsStream.csv")
write.csv(trainSearchStream, "trainSearchStream.csv")
